# Generated by Django 6.0.2 on 2026-02-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if user was rejected', null=True),
        ),
    ]
