# Generated by Django 6.0.2 on 2026-02-26 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the service', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description shown to users')),
                ('base_url', models.URLField(help_text='Base URL for API calls')),
                ('api_prefix', models.CharField(help_text='API prefix (e.g., /api/fulfil)', max_length=50)),
                ('ui_url', models.URLField(help_text='Frontend URL for user access')),
                ('icon', models.CharField(default='🔷', help_text='Emoji icon for display', max_length=10)),
                ('service_key', models.CharField(help_text='Secret key for service registration', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether service is active and visible')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_registered_at', models.DateTimeField(blank=True, help_text='Last time service registered', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
