# Generated by Django 6.0.2 on 2026-02-27 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User-provided name for this credential (e.g. 'YubiKey')", max_length=255)),
                ('credential_id', models.BinaryField(help_text='WebAuthn credential ID')),
                ('public_key', models.BinaryField(help_text='COSE public key bytes')),
                ('sign_count', models.PositiveIntegerField(default=0, help_text='Signature counter for clone detection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn Credential',
                'verbose_name_plural': 'WebAuthn Credentials',
                'ordering': ['-created_at'],
            },
        ),
    ]
