# Generated by Django 6.0.2 on 2026-02-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='Whether TOTP two-factor authentication is enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='TOTP secret for two-factor authentication', max_length=32, null=True),
        ),
    ]
