# Generated by Django 6.0.2 on 2026-02-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_totp_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webauthn_registration_challenge',
            field=models.TextField(blank=True, help_text='Temporary storage for WebAuthn registration challenge (base64)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='webauthn_registration_name',
            field=models.CharField(blank=True, help_text='Temporary storage for WebAuthn credential name during registration', max_length=255, null=True),
        ),
    ]
