# Generated by Django 6.0.2 on 2026-02-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_webauthn_registration_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webauthn_auth_challenge',
            field=models.TextField(blank=True, help_text='Temporary storage for WebAuthn authentication challenge (base64)', null=True),
        ),
    ]
