# Generated by Django 6.0.2 on 2026-02-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_webauthn_auth_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', help_text="User's role for access control", max_length=20),
        ),
    ]
